### ISSUE TITLE
Not Open Source

### ISSUE THREAD

**Issue by Aspie96** [ContributorCovenant/hippocratic-license#34] opened 2019-12-13 17:34 UTC
Note:
An issue already exists (issue #7) on this topic.
I will create another one, the reason will be apparent.

### Not Open Source
The term "open source" is primarely used by the Open Source Initiative, which asks not to use it for non open-source licenses.
Your license has not been approved (yet?) and is not open source.

It IS NOT a "license for Open Source Projects".
You also claim:

> The Hippocratic License is a living document, and has been open sourced.
No, it has not. The license of the project is not approved by OSI and this use of the term "open source" is confusing.

You have noticed it:
> https://twitter.com/CoralineAda/status/1176262778459496454

You have admitted that:

> the current structure of open source specifically prohibits us from protecting our labor from use by organizations
> https://twitter.com/CoralineAda/status/1176262778459496454

So please stop calling it "open source". It ain't.

### Comparison with another license
Please note: unlike you, the authors of the Vaccine License, also defined by Perens as an "ethical license", write:
> Until that approval is given, please do not refer to the Vaccine License as an Open Source license.

But you don't, and you should.

### Solution
As pointed out by @pearu, solution #9 would solve the problem.

### OSI doesn't "own" open source
Yes, it does.

The idea of "open source" has been popolarized by OSI and refers to licenses that follow the definition.

However, OSI approves licenses. Therefore, the term "open source" shouldn't just be applied to any license that in your opinion follows the criteria, but only to approved ones.

Please, read their FAQ (https://opensource.org/faq#approved-licenses-only and https://opensource.org/faq#avoid-unapproved-licenses).

If you don't like the Open Source Initative, or you don't agree with them, that is ok. Create your own idea and popularize it. Don't give it the same name.

### Why a new issue
The reason why this is an issue is that this license is an attempted appropriation of the term "open source".

Not only is this deeply unethical, it also creates confusion. Wether you agree with something or not, it is useful if we can know what we are talking about, in any conversation.
The term "open source" has a well known meaning. It does not simply relate to the availability of source code and has to do with OSI.

The reason I am opening a separate issue from #7 is that #7, although being an interesting and long discussion, in my opinion is very dispersive and focuses on multiple topic.
This is what I'd like to focus on:
* There are reasons why we should refer to OSI when talking about open source, even if OSI can't prevent misuse of the term with legal means.
* If something is not related with the idea thei popularized, it should not be referred as "open source". Even "ethical open source" is problematic because it contains "open source".
* Our own opinion on wether this license follows the OSD is irrelevant, because OSI has an approval process. This is not the case, for instance, for free software (of course this license isn't free either, but that's besides the point): the FSF lists licenses but doesn't approve them in the same way. Note that they don't approve all licenses that follow OSD: they, for instance, reject licenses which are too similar to previously existing ones.

If you think, as it seems, that you disagree with OSI and that software shouldn't be allowed to be used for evil, that's perfectly fair. Give this idea whatever name you want. "Ethical Source" seems to be what you are going for, and that is fair.

**Comment by Aspie96** [comment] 2019-12-13 20:40
> https://opensource.org/node/163
> Hey--if people want to try something that's not open source, great! But let them call it something else,

**Comment by paulyc** [comment] 2019-12-13 20:56
RMS? That you?

**Comment by rafaelcastrocouto** [comment] 2019-12-14 13:53
oh no ... not this again.

**Comment by TrevorFSmith** [comment] 2019-12-14 15:22
Let's mark as duplicate to #7 and move on.

We've heard the arguments pro and con and this Issues doesn't add to those lists.

**Comment by yawpitch** [comment] 2019-12-18 12:39
This is obviously a duplicate of #7 and states absolutely nothing new. Let's keep this contained to a single Issue.

**Closed as completed** 2019-12-18 15:22 UTC

**Comment by MrRawes** [comment] 2022-03-20 22:14
[well](https://opensource.org/blog/court-affirms-its-false-advertising-to-claim-software-is-open-source-when-its-not)
